#!/usr/bin/env python3
"""
triage-files.py — overnight idea-triage probe for case-study-04.

Asks a local LM Studio model to classify a list of repository files into
one of four buckets, with a one-line rationale per file:

  commit-now      — clearly belongs in the next commit; obvious value, low risk.
  review-first    — touch points, gotchas, or scope ambiguity; needs human eyes
                    before commit.
  archive         — outdated, superseded, or no longer relevant; remove or move
                    to an archive folder.
  build-artifact  — generated, regenerable, or vendored; should be gitignored
                    not committed.

This is the smallest expected output of any local-tier task: typically one short
line per file. The point of case-study-04 is to measure whether idea-triage
holds up as a strong-fit row on real data, not to produce a final commit plan.

Usage from a project root:

    python3 path/to/triage-files.py [options]

By default the script asks `git status --porcelain=v1` for the list of modified
and untracked files. Pass a file path with --files-from to use a hand-curated
list instead.

Common options:
    --files-from PATH       Hand-curated list (one path per line) instead of git status.
    --max-files N           Cap files sent. Default 0 = auto-scale against context.
    --lm-studio-context N   Loaded model's context length in tokens (default 16384).
    --sample-rate FLOAT     Mark ~this fraction of rows for human spot-check (0.0-1.0).
    --dry-run               Print the prompt that would be sent and exit.
    --model ID              Override loaded model id.
    --temperature FLOAT     Default 0.2.
    --max-tokens N          Default 4000.

Output:
    The bucket counts in the output are POST-PROCESSED — the script parses its
    own response and replaces the model's counts line with verified counts.
    Don't trust the model's arithmetic; trust the script's recomputation.

Local-only by design. Outputs:

    <project-root>/.sustaindev/measurement/triage-<timestamp>.md
    <project-root>/.sustaindev/measurement/triage-<timestamp>.json

Zero external dependencies (urllib + stdlib only).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


DEFAULT_LM_STUDIO_URL = "http://127.0.0.1:1234/v1/chat/completions"
DEFAULT_MODEL = "qwen/qwen3.5-9b"
DEFAULT_TEMPERATURE = 0.2
DEFAULT_MAX_TOKENS = 4000
DEFAULT_TIMEOUT = 600

PROJECT_LAYER_FILES = [
    "PROJECT_CONTEXT.md",
    "CODEMAP.md",
    "RISKS.md",
    "MAINTAINABILITY_NOTES.md",
]
# Note (v0.1.3): RISKS.md and MAINTAINABILITY_NOTES.md added based on
# case-study-04 finding #6 — without them the model defaults to confident
# commit-now classification and never flags risky files for review-first.
# AI_POLICY.md and DECISIONS.md are intentionally still excluded; they tend
# to be longer and less directly useful for triage-shaped decisions.

SYSTEM_PROMPT = """\
/no_think

You are a triage assistant for a software project. Your job is to classify each
file path the user lists into ONE of these four buckets:

  commit-now      — clearly belongs in the next commit. Source code, tests,
                    documentation, configuration that has been actively worked on
                    and is part of the project's intended state. Low risk to
                    commit immediately.
  review-first    — has touchpoints, scope ambiguity, or risk that warrants
                    human review before commit. Examples: large refactors of
                    sensitive code, files that change unrelated boundaries,
                    files where the user might have intended only a subset of
                    the changes.
  archive         — outdated, superseded, replaced, or no longer relevant.
                    Examples: old planning docs, deprecated implementation
                    files, stale review outputs.
  build-artifact  — generated by the build/runtime, vendored, or regenerable.
                    Should be gitignored and not committed. Examples: bin/, obj/,
                    node_modules/, dist/, *.lock files in some ecosystems,
                    OS metadata like .DS_Store, IDE cache directories.

Output rules — follow exactly:

1. Output a markdown table with three columns: File, Bucket, Rationale.
2. One row per file. Bucket value is exactly one of: commit-now, review-first,
   archive, build-artifact (lowercase, hyphenated, no quotes).
3. Rationale is ONE sentence, under 25 words. Cite the project context if
   relevant; otherwise explain by file extension or path pattern.
4. After the table, output exactly one summary line in this format:
   "Counts: commit-now=N, review-first=N, archive=N, build-artifact=N (total=N)"
5. Do not produce any other content. No preamble, no postamble, no <think>
   tags, no introduction, no closing summary beyond the counts line.

Specific rules that apply to particular file patterns:

- `.gitkeep` files are ALWAYS commit-now. They exist specifically to track
  otherwise-empty directories in git.
- Directory listings (paths ending in `/`) should be classified by likely
  contents, not by directory name alone. A `runtime-state/` directory might
  be build-artifact; a `runtime-state/` containing only a tracked `.gitkeep`
  is commit-now for the directory marker (the runtime contents themselves are
  separate concerns handled by .gitignore, not by this triage).
- If the project context lists a file under "hot spots", "stable anchors", or
  any "Hoog ernst" / "high severity" risk in RISKS.md, classify it as
  review-first regardless of how active or modified it appears. Hot-spot
  status implies "needs human eyes before commit."
- If a file is ambiguous and the project context gives no clear signal, prefer
  review-first over guessing.
"""


def fail(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(code)


def warn(msg: str) -> None:
    print(f"WARNING: {msg}", file=sys.stderr)


def utc_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def utc_filestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")


def list_changed_files(project_root: Path) -> list[str]:
    """Return modified + untracked paths from `git status --porcelain=v1`."""
    try:
        result = subprocess.run(
            ["git", "-C", str(project_root), "status", "--porcelain=v1"],
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        fail(f"git status failed: {e.stderr.strip()}")
    files: list[str] = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        # Lines look like "?? path", " M path", "MM path", etc.
        if len(line) >= 4:
            files.append(line[3:].strip())
    return files


def read_optional(path: Path, label: str) -> Optional[str]:
    if not path.is_file():
        warn(f"Skipping missing {label}: {path}")
        return None
    return path.read_text(encoding="utf-8")


def call_lm_studio(
    url: str,
    model: str,
    system_prompt: str,
    user_message: str,
    temperature: float,
    max_tokens: int,
    timeout: int,
) -> dict:
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url, data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            err_body = e.read().decode("utf-8", errors="replace")
        except Exception:
            err_body = "(no body)"
        fail(
            f"LM Studio rejected the request with HTTP {e.code} {e.reason}.\n"
            f"  Server said: {err_body}\n"
            f"  Common causes:\n"
            f"    - Model id mismatch (try --model with the loaded id).\n"
            f"    - Context length too small (LM Studio default is 4096; raise to >= 8192).\n"
            f"    - max_tokens too high for the loaded model.",
            code=5,
        )
    except urllib.error.URLError as e:
        fail(
            f"Could not reach LM Studio at {url}: {e}\n"
            f"  Is the local server running? Developer tab in LM Studio enables it.",
            code=2,
        )
    return {}


VALID_BUCKETS = ("commit-now", "review-first", "archive", "build-artifact")


def recompute_counts(table_text: str) -> tuple[str, dict, list[str]]:
    """Parse the model's output table and recompute the counts line.

    Returns (rewritten_text, counts_dict, anomalies). The model's reported
    counts line (if any) is removed from the body and replaced with a verified
    one. Anomalies lists any rows that didn't have a recognized bucket.
    """
    lines = table_text.splitlines()
    counts = {b: 0 for b in VALID_BUCKETS}
    anomalies: list[str] = []
    table_rows = 0
    body_lines: list[str] = []
    counts_line_pattern = re.compile(r"^Counts:\s*", re.IGNORECASE)
    for line in lines:
        # Drop any model-emitted counts line; we'll append our own.
        if counts_line_pattern.match(line.strip()):
            continue
        body_lines.append(line)
        # Parse table rows (skip header/separator).
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        bucket = cells[1]
        # Skip the header row and the separator row.
        if bucket == "Bucket" or set(bucket) <= set("- "):
            continue
        table_rows += 1
        if bucket in counts:
            counts[bucket] += 1
        else:
            anomalies.append(f"unrecognized bucket '{bucket}' on row: {cells[0]}")
    total = sum(counts.values())
    counts_line = (
        f"Counts (verified by post-processing): "
        f"commit-now={counts['commit-now']}, "
        f"review-first={counts['review-first']}, "
        f"archive={counts['archive']}, "
        f"build-artifact={counts['build-artifact']} "
        f"(total={total}; rows seen={table_rows})"
    )
    rewritten = "\n".join(body_lines).rstrip() + "\n\n" + counts_line + "\n"
    return rewritten, {**counts, "total": total, "table_rows": table_rows}, anomalies


def annotate_sample(table_text: str, sample_rate: float, seed: int = 0) -> str:
    """Mark a random subset of rows for human spot-check attention.

    Adds a leading 🔍 (or text marker if no unicode) to ~sample_rate fraction
    of rows. The marker shows up in the File column and signals "this row was
    randomly sampled; double-check it." Closes case-study-04 finding #10.
    """
    if sample_rate <= 0:
        return table_text
    import random

    rng = random.Random(seed)
    out_lines: list[str] = []
    for line in table_text.splitlines():
        if (
            line.startswith("|")
            and not line.startswith("| File")
            and not set(line.strip().strip("|")) <= set("- |")
        ):
            cells = line.strip().strip("|").split("|")
            if len(cells) >= 3 and rng.random() < sample_rate:
                # Mark the file cell.
                cells[0] = " [SAMPLED] " + cells[0].lstrip()
                line = "| " + " | ".join(c.strip() for c in cells) + " |"
        out_lines.append(line)
    return "\n".join(out_lines)


def extract_content(response: dict) -> tuple[str, str]:
    try:
        message = response["choices"][0]["message"]
    except (KeyError, IndexError) as e:
        fail(f"Unexpected response shape: {e}")
    raw = (message.get("content") or "").strip()
    reasoning = (message.get("reasoning_content") or "").strip()
    stripped = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
    if stripped:
        return stripped, reasoning
    if reasoning:
        warn("content empty; using reasoning_content as fallback (review carefully).")
        return reasoning, reasoning
    fail("Model returned no usable content.", code=4)
    return "", ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--project-root", default=os.getcwd())
    parser.add_argument("--files-from", default=None,
                        help="Path to a text file with one file path per line. "
                             "If omitted, the script runs `git status --porcelain` "
                             "in the project root.")
    parser.add_argument("--max-files", type=int, default=0,
                        help="Cap the number of files sent in one batch. Default 0 = "
                             "auto-scale against --lm-studio-context: roughly one file "
                             "per 100 tokens of available context after reserving room for "
                             "system prompt, project layer, and the output. Pass an integer "
                             "to override.")
    parser.add_argument("--lm-studio-context", type=int,
                        default=int(os.environ.get("LM_STUDIO_CONTEXT", "16384")),
                        help="The loaded LM Studio model's context length in tokens. "
                             "Used only for --max-files auto-scaling. Default 16384 "
                             "(or $LM_STUDIO_CONTEXT). Doesn't change the model's actual "
                             "context — set that in LM Studio.")
    parser.add_argument("--sample-rate", type=float, default=0.0,
                        help="Mark approximately this fraction of rows with [SAMPLED] for "
                             "human spot-check attention. Range 0.0-1.0. Default 0 = off. "
                             "Recommended: 0.10 (~10%) for unfamiliar projects.")
    parser.add_argument("--lm-studio-url", default=os.environ.get("LM_STUDIO_URL", DEFAULT_LM_STUDIO_URL))
    parser.add_argument("--model", default=os.environ.get("LM_STUDIO_MODEL", DEFAULT_MODEL))
    parser.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    parser.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS)
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the prompt that would be sent and exit.")
    parser.add_argument("-h", "--help", action="store_true")
    args = parser.parse_args()
    if args.help:
        print(__doc__)
        sys.exit(0)
    return args


def main() -> int:
    args = parse_args()
    project_root = Path(args.project_root).resolve()

    # Resolve file list.
    if args.files_from:
        files_path = Path(args.files_from).resolve()
        if not files_path.is_file():
            fail(f"--files-from not found: {files_path}")
        files = [line.strip() for line in files_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    else:
        files = list_changed_files(project_root)
    if not files:
        fail("No files to triage. Pass --files-from or have something in `git status`.")

    # Resolve max_files: explicit override, or auto-scale against context.
    if args.max_files > 0:
        max_files = args.max_files
    else:
        # Heuristic: reserve ~3,500 tokens for system prompt + project layer (with
        # RISKS.md and MAINTAINABILITY_NOTES added, this can grow); reserve
        # `max_tokens` for output; treat each file as ~80 input tokens (path +
        # rationale roundtrip). What's left is the per-file budget.
        reserved = 3500 + args.max_tokens
        budget = max(args.lm_studio_context - reserved, 4000)
        max_files = max(20, budget // 80)
        print(
            f"Auto-scaled --max-files to {max_files} (context={args.lm_studio_context}, "
            f"reserved={reserved}, budget={budget} tokens / 80 tokens/file).",
            file=sys.stderr,
        )

    if len(files) > max_files:
        warn(
            f"File count ({len(files)}) exceeds max_files ({max_files}); "
            f"truncating to first {max_files}. Re-run with --max-files higher, "
            f"--lm-studio-context higher (must match the loaded model's actual context), "
            f"or run in chunks if you want full coverage."
        )
        files = files[: max_files]

    # Gather optional context.
    context_blocks: list[str] = []
    for filename in PROJECT_LAYER_FILES:
        text = read_optional(project_root / filename, filename)
        if text is not None:
            context_blocks.append(f"### {filename}\n\n{text.strip()}")

    file_listing = "\n".join(f"- {f}" for f in files)
    user_message_parts = [
        "Project context (read-only, abbreviated; for any project-specific naming conventions or stack hints):",
        "",
    ]
    if context_blocks:
        user_message_parts.extend(context_blocks)
    else:
        user_message_parts.append("(no project layer files found — use file extensions and path patterns to classify)")
    user_message_parts.extend(
        [
            "",
            f"Files to classify ({len(files)} total):",
            "",
            file_listing,
            "",
            "Output the markdown table + counts line as specified by the system prompt. No other content.",
        ]
    )
    user_message = "\n".join(user_message_parts)

    if args.dry_run:
        print("=" * 60)
        print("DRY RUN: prompt that would be sent")
        print("=" * 60)
        print("--- system ---")
        print(SYSTEM_PROMPT)
        print("--- user ---")
        print(user_message[:4000])
        print(f"\n... user message total: {len(user_message)} chars")
        print("=" * 60)
        return 0

    measurement_dir = project_root / ".sustaindev" / "measurement"
    measurement_dir.mkdir(parents=True, exist_ok=True)
    stamp = utc_filestamp()
    out_md = measurement_dir / f"triage-{stamp}.md"
    out_json = measurement_dir / f"triage-{stamp}.json"

    print(f"Calling LM Studio ({args.model}) to triage {len(files)} files...", file=sys.stderr)
    t0 = time.perf_counter()
    response = call_lm_studio(
        args.lm_studio_url, args.model,
        SYSTEM_PROMPT, user_message,
        args.temperature, args.max_tokens, args.timeout,
    )
    elapsed = time.perf_counter() - t0
    raw_output, reasoning = extract_content(response)

    # Post-process: recompute counts (model arithmetic is unreliable per
    # case-study-04 finding #7) and optionally mark a sample for spot-check.
    output, verified_counts, anomalies = recompute_counts(raw_output)
    if args.sample_rate > 0:
        output = annotate_sample(output, args.sample_rate)
    for anomaly in anomalies:
        warn(f"Output anomaly: {anomaly}")

    usage = response.get("usage", {}) or {}
    out_md.write_text(
        f"# Triage Output ({utc_iso()})\n\n"
        f"Project root: `{project_root}`\n"
        f"File count (input): {len(files)}\n"
        f"Model: `{args.model}`\n"
        f"Wall-clock: {elapsed:.1f}s\n"
        f"Total tokens: {usage.get('total_tokens', 'n/a')}\n"
        f"Sample rate: {args.sample_rate}\n\n"
        f"---\n\n"
        f"{output}\n",
        encoding="utf-8",
    )
    out_json.write_text(
        json.dumps(
            {
                "task": "triage-files",
                "model": args.model,
                "endpoint": args.lm_studio_url,
                "wall_clock_s": round(elapsed, 2),
                "files_count": len(files),
                "prompt_tokens": usage.get("prompt_tokens"),
                "completion_tokens": usage.get("completion_tokens"),
                "total_tokens": usage.get("total_tokens"),
                "reasoning_chars": len(reasoning),
                "output_chars": len(output),
                "verified_counts": verified_counts,
                "output_anomalies": anomalies,
                "sample_rate": args.sample_rate,
                "lm_studio_context": args.lm_studio_context,
                "max_files_resolved": max_files,
                "output_md_path": str(out_md),
                "timestamp_utc": utc_iso(),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(
        f"Done. wall_clock={elapsed:.1f}s tokens={usage.get('total_tokens', 'n/a')} "
        f"files={len(files)} reasoning_chars={len(reasoning)} output_chars={len(output)}",
        file=sys.stderr,
    )
    print(f"Markdown: {out_md}", file=sys.stderr)
    print(f"JSON:     {out_json}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
